### ISSUE TITLE
HTTPS gives 502 Bad Gateway

### ISSUE THREAD

**Issue by lukastom** [genesisweb/valet-linux-plus#97]
I am on Linux Mint 21.1 Cinnamon. When using `secure`, the HTTPS site gives 502 Bad Gateway. The only solution that works is `sudo ln -s ~/.valet/valetXY.sock ~/.valet/valet.sock` (where XY is the number it uses, see the file in your file manager). Sounds like a dirty method but works for both HTTP and HTTPS.

There is another solution. Go to `/etc/php/8.2/fpm/pool.d/valet.conf` and edit this line: `listen = /home/user/.valet/valetXY.sock`. Just remove the XY number. Restart FPM. `sudo service php8.2-fpm restart`. Now, HTTPS will work but HTTP throws 502 Bad Gateway.

It feels that `valet.sock` for HTTPS is hardcoded somewhere, so it refuses to use `valetXY.sock` that is in the configuration file.

**Comment by uttam-praella** [comment]
@lukastom 

Could you please describe which version you are currently using? We've just released version v1.6.6. This issue is fixed with latest version.

You may need to run `valet use 8.2` command to fix config files.

**Comment by lukastom** [comment]
Dear @uttam-praella, thank you so much, that fixed it!! I upgraded to the newest version with `composer global update`, verified the version by `valet --version`. I am glad that I have the newest version now though it did not solve the problem immediately. After that I did `valet use 8.2` and `valet restart` and the problem is solved now! So, while it was important to have the newest version, I believe that `valet use 8.2` actually set the right configuration, exactly as you said.

**Comment by uttamrabadiya** [comment]
@lukastom 
Glad to hear that it fixed your issue. For the Mailhog, we've recently replaced it with Mailpit, so we changed the domain as well, you can try with `mails.test` domain, if it doesn't work then please share output of below commands:

```
sudo systemctl status mailpit
cat ~/.valet/Log/mails.test-error.log
cat ~/.valet/Log/nginx-error.log
```
